[workspace]
members = [
  "archive",
  "berkeleydb",
  "fingerprint",
  "snippets",
  "srclib",
  "traceconf",
  "tracer",
  "vsi",
]

[profile.dev.package.backtrace]
opt-level = 3

[profile.release]
lto = "fat"
