name: macOS

on: pull_request

jobs:
  build-and-test:
    runs-on: macOS-latest

    steps:
      # Install system dependencies
      - run: |
          brew install pkgconfig libarchive
          echo PKG_CONFIG_PATH=$(brew ls libarchive | grep .pc$ | sed 's|/libarchive.pc||') >> $GITHUB_ENV

      # Set up repo and toolchain
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      # Need a lock file for caching
      - run: cargo generate-lockfile
      - uses: Swatinem/rust-cache@v1.3.0
      
      # Check and test
      - uses: taiki-e/install-action@nextest
      - run: cargo check --release --all --bins --examples --tests
      - run: cargo nextest run
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
          FOSSA_ORG_ID: ${{ vars.FOSSA_ORG_ID }}
          # We should re-enable these but they're taking too long and I don't have time to dig into it right now.
          # ENABLE_NETWORK_TESTS: "1"
      # nextest doesn't run doctests, but does test everything else: https://github.com/nextest-rs/nextest/issues/16
      # run doctests after; this won't result in any extra rebuilds and is very quick.
      # doctest overview: https://doc.rust-lang.org/rustdoc/write-documentation/documentation-tests.html
      - run: cargo test --doc
