name: windows

on: pull_request

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      # Cache vcpkg database
      - uses: actions/cache@v3
        with:
          path: $VCPKG_ROOT/installed
          key: ${{ runner.os }}-vcpkg-cache-x64-windows-static
        env:
          VCPKG_ROOT: 'C:\vcpkg'
      - uses: actions/cache@v3
        with:
          path: $VCPKG_ROOT/downloads
          key: ${{ runner.os }}-vcpkg-cache-x64-windows-static
        env:
          VCPKG_ROOT: 'C:\vcpkg'

      # Install system dependencies
      - run: |
          vcpkg integrate install
          vcpkg install libarchive:x64-windows-static
        env:
          VCPKG_ROOT: 'C:\vcpkg'

      # Set up repo and toolchain
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      # Need a lock file for caching
      - run: cargo generate-lockfile
      - uses: Swatinem/rust-cache@v1.3.0
      
      # Check and test
      - uses: taiki-e/install-action@nextest
      - run: cargo check --release --all --bins --examples --tests
      - run: cargo nextest run
